echo
#!/bin/sh
#
echo "ZWNobwojIS9iaW4vc2gKIwoKd2dldCAtTyAvdG1wL2UyaXBsYXllci1weTMudGFyLmd6ICJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vdGFyZWt6b2thL2UyaXBsYXllci1weTMvbWFpbi9lMmlwbGF5ZXItcHkzLnRhci5neiIKCnRhciAteHpmIC90bXAvKi50YXIuZ3ogLUMgLwoKcm0gLXIgL3RtcC9lMmlwbGF5ZXItcHkzLnRhci5negoKZWNobyAiICAgICAgICAgVVBMT0FERUQgQlkgVEFSS19IQU5GWSAgICAiCgoKa2lsbGFsbCAtOSBlbmlnbWEyCgpzbGVlcCAyOw==" | base64 -d | sh

